### ISSUE TITLE
[Feature] Add `parse_http_headers` Function

### ISSUE THREAD

**Issue by xharpenParksuhyeon** [GDB-Online-Clone/http_web_server_c#13]
### 기능 설명
`parse_http_headers` 함수를 추가하여 HTTP 헤더 문자열을 파싱하고, 이를 `http_headers` 구조체로 변환하는 기능을 구현합니다.

### 구현 이유
HTTP 요청과 응답을 처리할 때 헤더 정보를 구조체 형태로 관리하기 위해, 헤더 문자열을 파싱하는 함수가 필요합니다. 이를 통해 헤더 정보의 접근성을 높이고 코드의 일관성을 유지할 수 있습니다.

### 구현 아이디어
- `parse_http_headers` 함수는 전체 헤더 문자열을 받아 개별 헤더를 키-값 쌍으로 분리하고, 이를 `http_headers` 구조체에 저장합니다.
- 이 함수는 헤더 파싱을 표준화하여, 후속 로직에서 헤더 정보를 쉽게 사용할 수 있도록 합니다.

### 추가 정보
다양한 형식의 헤더 문자열을 테스트하여, 파싱의 정확성과 구조체 저장 기능을 검증하는 것이 필요할 수 있습니다.

**Comment by sony-string** [comment]
(Commit c8bcb45) 기준 다음의 테스트 케이스를 통과합니다.

### 1. Input (Valid input)
```
no_quotes:   "value quotes with whitespace"<CRLF>
"key quotes with whitespace": value no quotes but whitespace<CRLF>
"quote with colon : ": trimmed_value<CRLF>
"quote; " is in key" :value4<CRLF>
  start_with_whitespace : "     " "  val"""ue5 "<CRLF><CRLF>
```

### 1. Output
- 각 줄은 하나의 헤더를 나타내고, 형식은 다음과 같습니다. "\<key> \<value>"
```
no_quotes value quotes with whitespace
key quotes with whitespace value no quotes but whitespace
quote with colon :  trimmed_value
quote; " is in key value4
start_with_whitespace : "     " "  val"""ue5 "
```

### 2. Input (Invalid input)
```
"error key :   "value1 one"<CRLF><CRLF>
```

### 2. Output 
- `INVALID` 는 테스트 코드에서 출력한 텍스트입니다.
```
INVALID
```
