### ISSUE TITLE
[Docs / Bug] Abnormal doxygen generated docs issue with @example tag in doxygen comments  

### ISSUE THREAD

**Issue by sony-string** [GDB-Online-Clone/http_web_server_c#67]
### 버그 설명
- doxygen 스타일 주석에서 \@example 태그가 의도와 다르게 문서를 생성하고 있습니다.
- 해당 주석의 마지막 수정자는 @jongyoung3 입니다. Assignee 지정하겠습니다.
- https://github.com/GDB-Online-Clone/http_web_server_c/blob/1ff1d75368159f37d3b7e2265f7fa3601f272063/src/http.h#L123

### 재현 방법
- doxygen을 통해 문서를 생성 시, @example 태그에 정의된 내용이 예상과 다른 형식으로 출력됩니다.
- 쉬운 확인을 위해 현재 1ff1d75 commit 시점 기준으로 `branch:feature/http-request` 의 doxygen 문서를 업로드하였습니다.
- [해당 example 문서](https://sony-string.net/GDB-Online-Clone/Http-Web-Server-C/branches/http-request/_2root_2code_2GDB-Online-Clone_2http_web_server_c_2src_2http_8h-example.html) 

### 기대 동작
@example 태그가 의도한 대로 문서를 생성해야 하며, 예제 내용이 정확히 반영되어야 합니다.

### 환경 정보
- **도구 버전**: doxygen 1.9.8

### 추가 정보
@example 태그의 사용 방법이나 설정에 문제가 있을 수 있습니다. 관련 설정과 태그 사용을 점검하고 수정 혹은 @sony-string 저에게 알려주시길 바랍니다.

**Comment by jongyoung3** [comment]
@sony-string @example 삭제했습니다.
